#!/bin/bash

XTERM="$APPDIR/usr/bin/xterm"
LIBDIR="$APPDIR/usr/lib"

# Ensure the $APPDIR is set correctly
export APPDIR=$(dirname "$(readlink -f "$0")")

# Set the library path to include AppDir/usr/lib
export LD_LIBRARY_PATH="$LIBDIR:$LD_LIBRARY_PATH"

# Launch xterm with the script inside the AppImage
$XTERM -T "Super Smash Bros. Ultimate Optimizer" -fa 'Monospace' -fs 14 -bg black -fg white -geometry 69x23 -hold -e "bash \"$APPDIR/usr/bin/ssbu-optimizer.sh\""

